package server.dto.exceptions;

public enum DtoErrorCode {
    WRONG_USER_NAME, WRONG_USER_SURNAME, WRONG_USER_PATRONYMIC,  WRONG_USER_LOGIN, WRONG_USER_PASSWORD, WRONG_USER_CHK_PASSWORD,
    EMPTY_FIELD
}
